"""
Semarchy YAML export converter.

Converts our Reltio matchGroups JSON into a Semarchy entity design YAML
with a matcher block, matchRules using SemQL conditions, and sensible
merge thresholds.

Semarchy key concepts used here:
  - SemQL condition:  Record1.Field = Record2.Field   (exact)
                      SEM_EDIT_DISTANCE_SIMILARITY(Record1.F, Record2.F) > 80  (fuzzy)
  - matchScore:       1-100  (automatic→100, suspect→85, relevance_based→70)
  - Merge thresholds: mergeThresholdNewGroup, mergeThresholdMergingConfirmed, etc.
  - useMultiIterationGrouping: true  (processes highest scores first)
  - useTransitiveMatchScore:   true  (transitive duplicate clustering)
"""

import re
from typing import Any


def _uri_to_field(uri: str) -> str:
    """Extract bare field name from a Reltio attribute URI."""
    return uri.rstrip("/").split("/")[-1]


def _exact_condition(uri: str) -> str:
    f = _uri_to_field(uri)
    return f"Record1.{f} = Record2.{f}"


def _fuzzy_condition(uri: str, threshold: int = 80) -> str:
    f = _uri_to_field(uri)
    return f"SEM_EDIT_DISTANCE_SIMILARITY(Record1.{f}, Record2.{f}) > {threshold}"


def _exact_or_null_condition(uri: str) -> str:
    f = _uri_to_field(uri)
    return (
        f"(Record1.{f} IS NULL OR Record2.{f} IS NULL "
        f"OR Record1.{f} = Record2.{f})"
    )


def _score_from_type(rule_type: str) -> int:
    return {"automatic": 100, "suspect": 85, "relevance_based": 70}.get(rule_type, 80)


def _indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in text.splitlines())


def reltio_to_semarchy_yaml(
    match_rules: dict,
    entity_type: str,
    auto_confirm_threshold: int = 95,
) -> str:
    """
    Convert a Reltio matchGroups dict to a Semarchy entity YAML matcher block.

    Returns a YAML string ready to paste into a Semarchy entity design file.
    """
    groups = match_rules.get("matchGroups", [])
    semarchy_rules: list[dict[str, Any]] = []

    for g in groups:
        # Skip negativeRule groups — Semarchy handles prevention via merge thresholds
        if "negativeRule" in g:
            continue

        rule     = g.get("rule", {})
        and_cl   = rule.get("and", {})
        rtype    = g.get("type", "suspect")
        label    = g.get("label", g.get("uri", "").split("/")[-1])
        name     = re.sub(r"[^A-Za-z0-9_]", "_",
                          g.get("uri", "").split("/")[-1])
        score    = _score_from_type(rtype)

        conditions: list[str] = []

        # Exact fields
        for uri in and_cl.get("exact", []):
            conditions.append(_exact_condition(uri))

        # Fuzzy fields
        for uri in and_cl.get("fuzzy", []):
            conditions.append(_fuzzy_condition(uri))

        # exactOrNull fields
        for uri in and_cl.get("exactOrNull", []):
            conditions.append(_exact_or_null_condition(uri))

        # Relevance-based: pull from weights
        for w in rule.get("weights", []):
            uri = w.get("attribute", "")
            if uri:
                conditions.append(_fuzzy_condition(uri, threshold=75))

        if not conditions:
            continue

        semarchy_rules.append({
            "name":      name,
            "label":     label,
            "condition": " AND\n        ".join(conditions),
            "score":     score,
            "rtype":     rtype,
        })

    if not semarchy_rules:
        return "# No convertible match rules found.\n"

    # Build YAML string manually (avoids pyyaml dependency)
    lines = [
        f"# Semarchy matcher for entity: {entity_type}",
        f"# Generated by Pre-MDM Sandbox · {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"# Paste this block inside your {entity_type} entity design file.",
        "",
        "matcher:",
        f"  _type: SemQLMatcher",
        f"  _name: {entity_type}Matcher",
        f"  autoConfirmGoldenThreshold: {auto_confirm_threshold}",
        f"  autoConfirmSingletons: false",
        f"  useMultiIterationGrouping: true",
        f"  useTransitiveMatchScore: true",
        "",
        "  # Merge thresholds (adjust to your data quality level)",
        "  mergeThresholdNewGroup: 85",
        "  mergeThresholdMergingConfirmed: 85",
        "  mergeThresholdMergingConfirmedWithNewMasters: 85",
        "  mergeThresholdMergingConfirmedWithUnconfirmed: 75",
        "  mergeThresholdMergingUnconfirmed: 75",
        "  mergeThresholdMergingUnconfirmedWithNewMasters: 70",
        "  mergeThresholdRemergingPreviouslySplit: 90",
        "",
        "  matchRules:",
    ]

    for r in semarchy_rules:
        lines += [
            f"    - _type: SemQLMatchRule",
            f"      _name: {r['name']}",
            f"      label: \"{r['label']}\"",
            f"      matchScore: {r['score']}",
            f"      # Rule type origin: {r['rtype']}",
            f"      condition: >-",
            f"        {r['condition']}",
            "",
        ]

    return "\n".join(lines)
